# Config for project reports

run_modules:
    - fastqc
    - fastq_screen
    - custom_content

table_columns_visible:
    FastQC:
        percent_duplicates: False

top_modules:
    - 'custom_content'
